### ISSUE TITLE
Text response

### ISSUE THREAD

**Issue by KORuL** [ShashiPrasadKushwaha/Questionnaire#1]
Good day! Very interesting and useful library! Tell me, please, is there an opportunity to make support for a text response from the user? EditText some sort. For a question like: "Suggest your option"

**Comment by ShashiPrasadKushwaha** [comment]
Hi @KORuL 

I am sure this is not relevant anymore with this much late reply.

>Just for future visitors or until I feel to add your request in this repo.

You can consider any of the below approach:
1. This [repo](https://github.com/kenmeidearu/surveylib) already implemented your request, I guess you have to sort it out as per your requirement.
2. Another approach is, make a `fragment` class, like `CheckBoxesFragment`. Add a new value `e.g. user_input` for `"question_type_name"` key in json-file. And using this(user_input) value make a `if-condition` to add newly created `fragment` into `fragmentArrayList` just as other fragments under method : `parsingData()`.

**Comment by ShashiPrasadKushwaha** [comment]
Closed this issue, since no response from @KORuL
