### ISSUE TITLE
send data

### ISSUE THREAD

**Issue by nlictic** [ShashiPrasadKushwaha/Questionnaire#2]
I would like to send the responses to a database on firebase

**Comment by ShashiPrasadKushwaha** [comment]
Hi @nlictic 

Follow this [StackOverFlow](https://stackoverflow.com/questions/36395552/saving-json-object-to-firebase-in-android) could help you out(maybe).
This [section](https://github.com/ShashiPrasadKushwaha/Questionnaire#want-to-send-result-in-json-format-see-the-answeractivityjava) is creating JSONArray/JSONObject (from GSON). With the help of GSON, you can create desired input format for Firebase.

> Although, working with firebase is not in the scope of this repo.

**Comment by ShashiPrasadKushwaha** [comment]
Closed this issue since no response from @nlictic .
